version: "3.7"
services:
    ui:
       #image: ubuntu
       build: ./ui/subscription-admin
       ports:
           - "80:80"
       links:
           - server
       depends_on:
            - server
       healthcheck:
            test: ["CMD", "curl", "http://localhost:80/"]
            interval: 20s
            timeout: 20s
            retries: 5
    server:
      build: ./server
      ports:
      - "8005:8005"
      healthcheck:
        test: ["CMD", "curl", "http://localhost:8005/health/"]
        interval: 20s
        timeout: 20s
        retries: 5
      environment:
        - MONGO_USER=admin
        - MONGO_PASS=admin
        - MONGO_DB=workshop
        - MONGO_SERVER=workshop-cluster.ajivk.mongodb.net     

# docker-compose build 
# docker-compose up -d
# docker-compose up


## docker-compose down