kind: Deployment
apiVersion: apps/v1
metadata:
  name: subscription-manager
spec:

  # 1. Cuantas copias queremos del pod?
  replicas: 1

  # 2. Como actualizar el pod?
  strategy: 
    type: Recreate

  # 3. Cuales pods son manejados en este deployment?
  selector:
    # Estos labels debe hacer match on los del pod
    matchLabels:
      app: subscription-manager
  
  # Configuracion del pod
  template:
    metadata:
      # Labels selectores para el pod en este deploymen
      labels:
        app: subscription-manager
    spec:
      containers:
        # nombre del contenedor y de la imagen
        - name: subscription-manager-backend
          image: subscription-manager-backend
          ports:
          # exponer puestos
          - containerPort: 8005
          # varibales de ambiente
          env:
            - name: MONGO_USER
              value: "abc"
            - name: MONGO_PASS
              value: "abc"
            - name: MONGO_DB
              value: "abc"
            - name: MONGO_SERVER
              value: "abc"
          resources:
            requests:
              memory: "128Mi"  
              cpu: "1"
            limits:
              memory: "512Mi"  
              cpu: 500m      